spring:
  datasource:
    url: ${SENTINEL_DATASOURCE_URL}
    username: ${SENTINEL_DATASOURCE_USERNAME}
    password: ${SENTINEL_DATASOURCE_PASSWORD}

sentinel:
  security:
    agent:
      api-key: ${SENTINEL_AGENT_API_KEY}
    admin:
      username: ${SENTINEL_ADMIN_USERNAME}
      password: ${SENTINEL_ADMIN_PASSWORD}

logging:
  level:
    root: INFO
    br.com.sentinelx.core: INFO